language: java
jdk:
- openjdk11

script:
- mvn test
after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - fmariotti@fi.uba.ar
      - amore@fi.uba.ar
      - alasinofranco3@gmail.com
      - franfusco99@gmail.com
    on_failure: always
